import Cover1 from '../assets/book-cover-1.svg';
import Cover2 from '../assets/book-cover-2.svg';
import Cover3 from '../assets/book-cover-3.svg';
import Cover4 from '../assets/book-cover-4.svg';
import Cover5 from '../assets/book-cover-5.svg';
import Cover6 from '../assets/book-cover-6.svg';
import Cover7 from '../assets/book-cover-7.svg';
import Cover8 from '../assets/book-cover-8.svg';
import Cover9 from '../assets/book-cover-9.svg';
import Cover10 from '../assets/book-cover-10.svg';

export const data = [
    {
        id: '1',
        title: "Harry Potter and the Philosopher's Stone",
        author: 'J.K. Rowling',
        cover: Cover1,
        rate: '5',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '2',
        title: "The Shining",
        author: 'Stephen King',
        cover: Cover2,
        rate: '4',
        status: false,
        downloads: '430,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '3',
        title: "The Lord of the Rings",
        author: 'J.R.R. Tolkien',
        cover: Cover3,
        rate: '5',
        status: false,
        downloads: '1,700,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '4',
        title: "The Handmaid's Tale",
        author: 'Margaret Atwood',
        cover: Cover4,
        rate: '3',
        status: false,
        downloads: '2,300,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '5',
        title: "1984",
        author: 'George Orwell',
        cover: Cover5,
        rate: '5',
        status: false,
        downloads: '250,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '6',
        title: "To Kill a Mockingbird",
        author: 'Harper Leet',
        cover: Cover6,
        rate: '2',
        status: false,
        downloads: '6,400,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '7',
        title: "One Hundred Years of Solitude",
        author: 'Gabriel García Márquez',
        cover: Cover7,
        rate: '5',
        status: false,
        downloads: '3,300,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '8',
        title: "Pride and Prejudice",
        author: 'Jane Austen',
        cover: Cover8,
        rate: '4',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '9',
        title: "Great Expectations",
        author: 'Charles Dickens',
        cover: Cover9,
        rate: '2',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '10',
        title: "The Handmaid's Tale",
        author: 'Margaret Atwood',
        cover: Cover10,
        rate: '5',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '11',
        title: "Potter and the Philosopher's Stone",
        author: 'Rowling',
        cover: Cover1,
        rate: '4',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '12',
        title: "Shining",
        author: 'King',
        cover: Cover2,
        rate: '3',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '13',
        title: "Lord of the Rings",
        author: 'Tolkien',
        cover: Cover3,
        rate: '1',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '14',
        title: "Handmaid's Tale",
        author: 'Atwood',
        cover: Cover4,
        rate: '5',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '15',
        title: "2984",
        author: 'Orwell',
        cover: Cover5,
        rate: '4',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '16',
        title: "Kill a Mockingbird",
        author: 'Leet',
        cover: Cover6,
        rate: '4',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '17',
        title: "Hundred Years of Solitude",
        author: 'García Márquez',
        cover: Cover7,
        rate: '4',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '18',
        title: "Prejudice",
        author: 'Austen',
        cover: Cover8,
        rate: '3',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '19',
        title: "Expectations",
        author: 'Dickens',
        cover: Cover9,
        rate: '3',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '20',
        title: "Handmaid's Tale",
        author: 'Atwood',
        cover: Cover10,
        rate: '3',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '21',
        title: "Ehilosopher's Stone",
        author: 'Towling',
        cover: Cover1,
        rate: '1',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '22',
        title: "Fhining",
        author: 'Hing',
        cover: Cover2,
        rate: '5',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '23',
        title: "Rings",
        author: 'Molkien',
        cover: Cover3,
        rate: '3',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '24',
        title: "Tale",
        author: 'Vatwood',
        cover: Cover4,
        rate: '3',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '25',
        title: "7984",
        author: 'Dorwell',
        cover: Cover5,
        rate: '5',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '26',
        title: "Mockingbird",
        author: 'Teet',
        cover: Cover6,
        rate: '4',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '27',
        title: "Solitude",
        author: 'Márquez',
        cover: Cover7,
        rate: '5',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '28',
        title: "Wrejudice",
        author: 'Pusten',
        cover: Cover8,
        rate: '2',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },
    {
        id: '29',
        title: "Rexpectations",
        author: 'Pickens',
        cover: Cover9,
        rate: '5',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    
    },
    {
        id: '30',
        title: "For Handmaid's Tale",
        author: 'Batwood',
        cover: Cover10,
        rate: '3',
        status: false,
        downloads: '1,000,000',
        description: 'For the first time in his life, Harry Potter learns that he is not an ordinary boy. He is a wizard, and his parents were wizards. At the age of eleven, Harry goes to Hogwarts School of Witchcraft and Wizardry, where he makes new friends, learns a lot about the wizarding world, and begins to fight evil.',
        reviews: ['This is my all-time favorite book. It is magical, exciting, and inspiring.', 'Maria, 25 years old', 'I read this book when I was a child, and it changed my life. It taught me to believe in myself and my dreams.', 'Vlad, 30 years old'],
    },


]


export const mockData = (count) => {
    return data.slice(0, count);
}
